apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
    lab: lab2
spec:
  imagePullSecrets:
  - name: ghcr-secret 
  containers:
  - name: go-app
    image: ghcr.io/vld555/containers-lab-1/app:latest
    ports:
    - containerPort: 8080